const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Tween,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{bgstory: 0},
	{start: 0},
	{Mouse: 0},
	{Audio: 0},
	{storyText: 0},
	{iconPlay: 0},
	{skipstory: 0},
	{Keyboard: 0},
	{atasan: 0},
	{pintu: 0},
	{lukisan1: 0},
	{lukisan2: 0},
	{det1: 0},
	{det2: 0},
	{lukisan7: 0},
	{lukisan6: 0},
	{lukisan8: 0},
	{wallLamp: 0},
	{light3: 0},
	{papaninvestigasi: 0},
	{invest2: 0},
	{Solid: 0},
	{lantai2: 0},
	{health: 0},
	{canBeHit: 0},
	{isDead: 0},
	{isWalking: 0},
	{isHurt: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{char: 0},
	{TiledBackground2: 0},
	{npc_trigger: 0},
	{GUI_massage: 0},
	{smallmetal: 0},
	{dialog: 0},
	{dialogArray: 0},
	{next: 0},
	{Touch: 0},
	{Anchor: 0},
	{kantor: 0},
	{lantai3: 0},
	{lantai4: 0},
	{bg_lantai: 0},
	{bg3: 0},
	{pecah: 0},
	{semak: 0},
	{jendelah: 0},
	{light: 0},
	{nyawa: 0},
	{titleGame: 0},
	{enter_room_collision: 0},
	{isValue: 0},
	{box: 0},
	{barrel: 0},
	{medkit: 0},
	{Fade: 0},
	{splashShoot: 0},
	{damage: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{peluru: 0},
	{GuideTitle: 0},
	{GuideText: 0},
	{textPlay: 0},
	{Tween: 0},
	{MoveTo: 0},
	{bghitam: 0},
	{GameStartButton: 0},
	{bghome: 0},
	{minValue: 0},
	{maxValue: 0},
	{amunisi: 0},
	{bgAmmo: 0},
	{ammoText: 0},
	{isHit: 0},
	{mele_attack_splash: 0},
	{hp: 0},
	{isAttack: 0},
	{isCanMove: 0},
	{walk: 0},
	{LineOfSight: 0},
	{musuh: 0},
	{darah: 0},
	{hitbox_musuh: 0},
	{health_bar: 0},
	{heart: 0},
	{health_bar2: 0},
	{heart2: 0},
	{health_bar3: 0},
	{isValue2: 0},
	{kertas_jatuh: 0},
	{wanted: 0},
	{Sine: 0},
	{game_over: 0},
	{Pin: 0},
	{img1: 0},
	{picked: 0},
	{grid: 0},
	{bb: 0},
	{Text: 0},
	{finish: 0},
	{next2: 0},
	{asset_kertasDitangan: 0},
	{button: 0},
	{narasi1: 0},
	{narasi2: 0},
	{narasi3: 0},
	{ChatGPT_Image_Oct_6__2025__08_49_17_PMremovebgpreview: 0},
	{ambil: 0},
	{laporan1: 0},
	{laporan2: 0},
	{laporan3: 0},
	{Text2: 0},
	{tutup: 0},
	{terima_laporan: 0},
	{arsip: 0},
	{close: 0},
	{bghome2: 0},
	{Family1: 0},
	{dialogIndex: 0},
	{isCanMeleAttack: 0},
	{isDialogActive: 0},
	{IsRightView: 0},
	{IsCanShoot: 0},
	{amunityInventory: 0},
	{StepCharacter: 0},
	{char_stamina: 0},
	{dialogIndex2: 0},
	{isDialogActive2: 0},
	{isTextUp: 0},
	{dialogIndex4: 0},
	{isDialogActive4: 0}
];

self.InstanceType = {
	bgstory: class extends self.ISpriteInstance {},
	start: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	storyText: class extends self.ITextInstance {},
	iconPlay: class extends self.ISpriteInstance {},
	skipstory: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	atasan: class extends self.ISpriteInstance {},
	pintu: class extends self.ISpriteInstance {},
	lukisan1: class extends self.ISpriteInstance {},
	lukisan2: class extends self.ISpriteInstance {},
	det1: class extends self.ISpriteInstance {},
	det2: class extends self.ISpriteInstance {},
	lukisan7: class extends self.ISpriteInstance {},
	lukisan6: class extends self.ISpriteInstance {},
	lukisan8: class extends self.ISpriteInstance {},
	wallLamp: class extends self.ISpriteInstance {},
	light3: class extends self.ISpriteInstance {},
	papaninvestigasi: class extends self.ISpriteInstance {},
	invest2: class extends self.ISpriteInstance {},
	lantai2: class extends self.ISpriteInstance {},
	char: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	npc_trigger: class extends self.ISpriteInstance {},
	GUI_massage: class extends self.ISpriteInstance {},
	smallmetal: class extends self.ISpriteInstance {},
	dialog: class extends self.ITextInstance {},
	dialogArray: class extends self.IArrayInstance {},
	next: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	kantor: class extends self.ITextInstance {},
	lantai3: class extends self.ISpriteInstance {},
	lantai4: class extends self.ISpriteInstance {},
	bg_lantai: class extends self.ISpriteInstance {},
	bg3: class extends self.ITiledBackgroundInstance {},
	pecah: class extends self.ISpriteInstance {},
	semak: class extends self.ISpriteInstance {},
	jendelah: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	nyawa: class extends self.ISpriteInstance {},
	titleGame: class extends self.ITextInstance {},
	enter_room_collision: class extends self.ISpriteInstance {},
	box: class extends self.ISpriteInstance {},
	barrel: class extends self.ISpriteInstance {},
	medkit: class extends self.ISpriteInstance {},
	splashShoot: class extends self.ISpriteInstance {},
	peluru: class extends self.ISpriteInstance {},
	GuideTitle: class extends self.ITextInstance {},
	GuideText: class extends self.ITextInstance {},
	textPlay: class extends self.ITextInstance {},
	bghitam: class extends self.ITiledBackgroundInstance {},
	GameStartButton: class extends self.ISpriteInstance {},
	bghome: class extends self.ISpriteInstance {},
	amunisi: class extends self.ISpriteInstance {},
	bgAmmo: class extends self.ISpriteInstance {},
	ammoText: class extends self.ITextInstance {},
	mele_attack_splash: class extends self.ISpriteInstance {},
	musuh: class extends self.ISpriteInstance {},
	darah: class extends self.IParticlesInstance {},
	hitbox_musuh: class extends self.ISpriteInstance {},
	health_bar: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	health_bar2: class extends self.ISpriteInstance {},
	heart2: class extends self.ISpriteInstance {},
	health_bar3: class extends self.ISpriteInstance {},
	kertas_jatuh: class extends self.ISpriteInstance {},
	wanted: class extends self.ISpriteInstance {},
	game_over: class extends self.ISpriteInstance {},
	img1: class extends self.ISpriteFontInstance {},
	grid: class extends self.ISpriteInstance {},
	bb: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	finish: class extends self.ITextInstance {},
	next2: class extends self.ITextInstance {},
	asset_kertasDitangan: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	narasi1: class extends self.ITextInstance {},
	narasi2: class extends self.ITextInstance {},
	narasi3: class extends self.ITextInstance {},
	ChatGPT_Image_Oct_6__2025__08_49_17_PMremovebgpreview: class extends self.ISpriteInstance {},
	ambil: class extends self.ITextInstance {},
	laporan1: class extends self.ISpriteInstance {},
	laporan2: class extends self.ISpriteInstance {},
	laporan3: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	tutup: class extends self.ITextInstance {},
	terima_laporan: class extends self.ITextInstance {},
	arsip: class extends self.ISpriteInstance {},
	close: class extends self.ITextInstance {},
	bghome2: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}